// Study Shelf workspace: private collections, study queue, requests, reminders, and offline reading shortcuts in a single calm dashboard.
import AuthLoading from "@/components/AuthLoading";
import SignInGate from "@/components/SignInGate";
import { useAuth } from "@/_core/hooks/useAuth";
import { isExternalDeployment } from "@/lib/supabase";
import { createCollection, createReminder, createRequest, loadWorkspace, markReminderDone, readOfflineItems, updateQueue, type QueueStatus, type WorkspaceRequest } from "@/lib/studyWorkspace";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, BellRing, BellPlus, BookMarked, CheckCircle2, ClipboardList, FolderPlus, ListChecks, Loader2, Plus, Radio, Sparkles } from "lucide-react";
import { requestStudyNotifications } from "@/components/ReminderNotifier";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

const collectionColors = ["lilac", "sage", "sky", "peach", "butter", "rose"];

export default function StudySpace() {
  const { user, loading, isAuthenticated } = useAuth();
  const queryClient = useQueryClient();
  const [collectionName, setCollectionName] = useState("");
  const [collectionDescription, setCollectionDescription] = useState("");
  const [requestTitle, setRequestTitle] = useState("");
  const [requestCourse, setRequestCourse] = useState("");
  const [requestDetails, setRequestDetails] = useState("");
  const [requestUrgency, setRequestUrgency] = useState<WorkspaceRequest["urgency"]>("normal");
  const [reminderTitle, setReminderTitle] = useState("");
  const [reminderAt, setReminderAt] = useState("");
  const workspace = useQuery({ queryKey: ["study-workspace", user?.id], queryFn: () => loadWorkspace(String(user!.id)), enabled: isExternalDeployment && isAuthenticated && Boolean(user?.id), staleTime: 30_000 });
  const offlineItems = useMemo(() => readOfflineItems(), [workspace.dataUpdatedAt]);
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["study-workspace", user?.id] });
  const collectionMutation = useMutation({ mutationFn: () => createCollection(String(user!.id), collectionName, collectionDescription, collectionColors[(workspace.data?.collections.length ?? 0) % collectionColors.length]), onSuccess: () => { setCollectionName(""); setCollectionDescription(""); void invalidate(); toast.success("Collection created."); }, onError: error => toast.error(error instanceof Error ? error.message : "Collection could not be created.") });
  const requestMutation = useMutation({ mutationFn: () => createRequest(String(user!.id), requestTitle, requestCourse, requestDetails, requestUrgency), onSuccess: () => { setRequestTitle(""); setRequestCourse(""); setRequestDetails(""); void invalidate(); toast.success("Contribution request added."); }, onError: error => toast.error(error instanceof Error ? error.message : "Request could not be added.") });
  const reminderMutation = useMutation({ mutationFn: () => createReminder(String(user!.id), reminderTitle, reminderAt), onSuccess: () => { setReminderTitle(""); setReminderAt(""); void invalidate(); toast.success("Revision reminder set."); }, onError: error => toast.error(error instanceof Error ? error.message : "Reminder could not be set.") });
  const changeQueue = useMutation({ mutationFn: ({ noteId, status }: { noteId: string; status: QueueStatus }) => updateQueue(noteId, String(user!.id), { status }), onSuccess: () => void invalidate(), onError: () => toast.error("Queue state could not be updated.") });
  const finishReminder = useMutation({ mutationFn: ({ id, isDone }: { id: string; isDone: boolean }) => markReminderDone(id, isDone), onSuccess: () => void invalidate(), onError: () => toast.error("Reminder could not be updated.") });

  if (loading) return <AuthLoading label="Opening your study space" />;
  if (!isAuthenticated) return <SignInGate title="Make the shelf your own." description="Sign in to organize collections, build a study queue, keep annotations private, and receive revision reminders." />;
  if (!isExternalDeployment) return <main className="container py-20"><p className="eyebrow">Study Space</p><h1 className="mt-5 text-5xl text-[#151c4a]">Your workspace opens on the shared shelf.</h1></main>;
  if (workspace.isLoading || !workspace.data) return <main className="container py-20"><Loader2 className="h-6 w-6 animate-spin text-[#151c4a]" /></main>;
  const { collections, queue, requests, reminders } = workspace.data;
  const upcoming = reminders.filter(reminder => !reminder.isDone).slice(0, 4);
  return <main className="workspace-page container py-8 pb-24 sm:py-12">
    <section className="workspace-hero"><div><p className="eyebrow">Your private study workspace</p><h1>Arrange the work,<br /><i>then get into it.</i></h1><p>Collections, revision intent, and small commitments—kept close to the shelf without crowding it.</p></div><div className="workspace-stat-row"><Stat icon={<BookMarked />} label="Collections" value={collections.length} /><Stat icon={<ListChecks />} label="In your queue" value={queue.filter(item => item.status !== "reviewed").length} /><Stat icon={<BellRing />} label="Upcoming" value={upcoming.length} /></div></section>
    <div className="workspace-grid">
      <section className="workspace-card workspace-card--wide"><header><div><span className="workspace-kicker"><Archive className="h-3.5 w-3.5" />Collections</span><h2>Build shelves around a real outcome.</h2></div><Link href="/" className="editorial-text-button">Browse materials</Link></header><form className="workspace-inline-form" onSubmit={event => { event.preventDefault(); if (collectionName.trim()) collectionMutation.mutate(); }}><input value={collectionName} onChange={event => setCollectionName(event.target.value)} placeholder="Collection name — e.g. Calculus midterm" maxLength={80} /><input value={collectionDescription} onChange={event => setCollectionDescription(event.target.value)} placeholder="Optional focus" maxLength={300} /><button type="submit" disabled={collectionMutation.isPending || !collectionName.trim()}><Plus className="h-4 w-4" />Create</button></form><div className="collection-strip">{collections.length ? collections.map(collection => <article key={collection.id} className={`collection-tile collection-tile--${collection.color}`}><span>{collection.itemCount} item{collection.itemCount === 1 ? "" : "s"}</span><h3>{collection.name}</h3><p>{collection.description || "A quiet place for the material that belongs together."}</p></article>) : <Empty icon={<FolderPlus />} title="Start your first collection" text="Save a note to a collection from any note detail page." />}</div></section>
      <section className="workspace-card"><header><div><span className="workspace-kicker"><ListChecks className="h-3.5 w-3.5" />Smart queue</span><h2>What is worth attention next?</h2></div></header><div className="queue-list">{queue.length ? queue.map(item => <article key={item.noteId} className="queue-item"><div><span className="queue-item__course">{item.note?.course || "Study material"}</span><Link href={`/notes/${item.noteId}`}>{item.note?.title || "Unavailable material"}</Link></div><select value={item.status} onChange={event => changeQueue.mutate({ noteId: item.noteId, status: event.target.value as QueueStatus })} aria-label={`Update queue status for ${item.note?.title || "note"}`}><option value="up_next">Up next</option><option value="in_progress">In progress</option><option value="reviewed">Reviewed</option></select></article>) : <Empty icon={<ClipboardList />} title="Your queue is clear" text="Add materials from a note detail page, then move them through your study flow." />}</div></section>
      <section className="workspace-card"><header><div><span className="workspace-kicker"><BellRing className="h-3.5 w-3.5" />Revision reminders</span><h2>Give future-you a gentle cue.</h2></div><button className="workspace-notification-button" type="button" onClick={() => void requestStudyNotifications().then(() => toast.success("Device reminders are enabled.")).catch(error => toast.message(error instanceof Error ? error.message : "Device notifications remain off."))}><BellPlus className="h-3.5 w-3.5" />Enable device alerts</button></header><form className="workspace-reminder-form" onSubmit={event => { event.preventDefault(); if (reminderTitle.trim() && reminderAt) reminderMutation.mutate(); }}><input value={reminderTitle} onChange={event => setReminderTitle(event.target.value)} placeholder="What should you revisit?" maxLength={180} /><input type="datetime-local" value={reminderAt} onChange={event => setReminderAt(event.target.value)} /><button type="submit" disabled={reminderMutation.isPending || !reminderTitle.trim() || !reminderAt}>Set reminder</button></form><div className="reminder-list">{upcoming.length ? upcoming.map(reminder => <button key={reminder.id} type="button" onClick={() => finishReminder.mutate({ id: reminder.id, isDone: true })}><CheckCircle2 className="h-4 w-4" /><span><strong>{reminder.title}</strong><small>{new Date(reminder.reminderAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</small></span></button>) : <Empty icon={<BellRing />} title="Nothing scheduled" text="Set a reminder for a difficult topic or a material you want to revisit." />}</div></section>
      <section className="workspace-card"><header><div><span className="workspace-kicker"><Radio className="h-3.5 w-3.5" />Contribution requests</span><h2>Ask the shelf for what is missing.</h2></div></header><form className="workspace-request-form" onSubmit={event => { event.preventDefault(); if (requestTitle.trim() && requestCourse.trim()) requestMutation.mutate(); }}><input value={requestTitle} onChange={event => setRequestTitle(event.target.value)} placeholder="What do you need?" maxLength={180} /><input value={requestCourse} onChange={event => setRequestCourse(event.target.value)} placeholder="Course or subject" maxLength={180} /><textarea value={requestDetails} onChange={event => setRequestDetails(event.target.value)} placeholder="Optional context, scope, or week" maxLength={1200} rows={2} /><select value={requestUrgency} onChange={event => setRequestUrgency(event.target.value as WorkspaceRequest["urgency"])}><option value="low">Low urgency</option><option value="normal">Normal urgency</option><option value="high">High urgency</option></select><button type="submit" disabled={requestMutation.isPending || !requestTitle.trim() || !requestCourse.trim()}>Post request</button></form><div className="request-list">{requests.slice(0, 3).map(request => <article key={request.id}><span className={`request-urgency request-urgency--${request.urgency}`}>{request.urgency}</span><div><strong>{request.title}</strong><small>{request.course} · {request.status}</small></div></article>)}</div></section>
      <section className="workspace-card workspace-card--wide workspace-offline"><div><span className="workspace-kicker"><Sparkles className="h-3.5 w-3.5" />Offline reading list</span><h2>Keep the next layer of reading close.</h2><p>{offlineItems.length ? `${offlineItems.length} item${offlineItems.length === 1 ? "" : "s"} saved locally for quick return.` : "Save a material locally from its detail page. Its information will stay close at hand, even before you reconnect."}</p></div><div className="workspace-offline__notes">{offlineItems.slice(0, 3).map(item => <Link key={item.note.id} href={`/notes/${item.note.id}`}>{item.note.title}</Link>)}</div></section>
    </div>
  </main>;
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div><span>{icon}</span><strong>{value}</strong><small>{label}</small></div>; }
function Empty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="workspace-empty"><span>{icon}</span><div><strong>{title}</strong><p>{text}</p></div></div>; }
